nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:3000'] # Frontend autorisé
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': # Chemins pour lesquels appliquer les règles CORS
            allow_origin: ['http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
